/**
 * Walks fixtures/recorded/** and fixtures/corpus/** and emits two committed
 * TypeScript modules:
 *   - fixtures/recorded.generated.ts — RECORDINGS map + RECORDINGS_HASH
 *   - src/corpus/bundled.generated.ts — the corpus, threads, and cast as a
 *     plain module
 *
 * These are what the browser Evals tab imports (via a dynamic import inside
 * the "Run evals" handler, per the build plan, so other tabs' bundles stay
 * clean) instead of fetching anything at runtime — zero network calls, zero
 * API key, for the browser eval run. `npm run build` depends on this script
 * (see package.json's build script), and both generated files are committed
 * so a reviewer's clean clone has them without needing to run this script
 * themselves.
 */

import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { sha256Hex } from "../src/core/util/sha256.ts";
import { stableStringify } from "../src/core/util/stable-sort.ts";

const ROOT = join(import.meta.dirname, "..");

function readJsonIfExists(path: string): unknown {
  if (!existsSync(path)) return undefined;
  return JSON.parse(readFileSync(path, "utf8"));
}

function generateRecordingsModule(): void {
  const recordedDir = join(ROOT, "fixtures", "recorded");
  const recordings: Record<string, unknown> = {};

  for (const tier of ["extraction", "adjudication", "embedding"]) {
    const tierDir = join(recordedDir, tier);
    if (!existsSync(tierDir)) continue;
    for (const file of readdirSync(tierDir)) {
      if (!file.endsWith(".json")) continue;
      const call = JSON.parse(readFileSync(join(tierDir, file), "utf8"));
      recordings[call.key] = call;
    }
  }

  const sortedKeys = Object.keys(recordings).sort();
  const recordingsHash = sha256Hex(
    stableStringify(sortedKeys.map((k) => ({ key: k, responseText: (recordings[k] as { response: { text: string } }).response.text }))),
  );

  const banner = `// GENERATED by scripts/generate-bundles.ts. Do not edit by hand.
// Run \`npm run gen:bundles\` (or \`npm run record\`, which calls it) to regenerate.
// Committed to git so a clean clone can run the Evals tab with zero API calls.
//
// \`recordedAt\` is cast through \`unknown\` because \`Instant\` is a nominally
// branded type (see src/core/time.ts) and a JSON literal is plain \`string\`.
// recordedAt is metadata about when the recording was made, never read by
// graded logic (which only ever uses asOf/timestamp fields the pipeline
// itself supplies), so this cast carries no correctness risk.
`;
  const body =
    banner +
    `import type { RecordedCall } from "../src/core/types.ts";\n\n` +
    `export const RECORDINGS: Record<string, RecordedCall> = ${JSON.stringify(recordings, null, 2)} as unknown as Record<string, RecordedCall>;\n\n` +
    `export const RECORDINGS_HASH = ${JSON.stringify(recordingsHash)};\n`;

  writeFileSync(join(ROOT, "fixtures", "recorded.generated.ts"), body, "utf8");
  console.log(`Wrote fixtures/recorded.generated.ts (${sortedKeys.length} recordings, hash ${recordingsHash.slice(0, 12)}...)`);
}

function generateCorpusModule(): void {
  const messages = (readJsonIfExists(join(ROOT, "fixtures/corpus/messages.json")) as { messages?: unknown[] })?.messages ?? [];
  const threads = (readJsonIfExists(join(ROOT, "fixtures/corpus/threads.json")) as { threads?: unknown[] })?.threads ?? [];
  const cast = (readJsonIfExists(join(ROOT, "fixtures/corpus/cast.json")) as { cast?: unknown[] })?.cast ?? [];

  const banner = `// GENERATED by scripts/generate-bundles.ts. Do not edit by hand.
// Source of truth is fixtures/corpus/*.json — edit those, then re-run
// \`npm run gen:bundles\`.
//
// Timestamps are cast through \`unknown\` because \`Instant\` is a nominally
// branded type (see src/core/time.ts) and a JSON literal is plain \`string\`.
// This is safe specifically because validate-corpus.ts (run in CI/locally
// before committing corpus changes) already asserts every message
// timestamp matches the explicit-offset ISO-8601 pattern parseInstant()
// requires — the brand is re-asserted structurally, not bypassed silently.
`;
  const body =
    banner +
    `import type { Message, Thread, CastEntry } from "../core/types.ts";\n\n` +
    `export const MESSAGES: Message[] = ${JSON.stringify(messages, null, 2)} as unknown as Message[];\n\n` +
    `export const THREADS: Thread[] = ${JSON.stringify(threads, null, 2)};\n\n` +
    `export const CAST: CastEntry[] = ${JSON.stringify(cast, null, 2)};\n`;

  const outDir = join(ROOT, "src", "corpus");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "bundled.generated.ts"), body, "utf8");
  console.log(`Wrote src/corpus/bundled.generated.ts (${(messages as unknown[]).length} messages, ${(threads as unknown[]).length} threads, ${(cast as unknown[]).length} cast entries)`);
}

generateRecordingsModule();
generateCorpusModule();
